name: freestyle_speed_dial
description: A lightweight yet powerful speed dial widget for Flutter, offering full control over the appearance, layout and animations of the speed dial.
version: 1.0.1+2
homepage: https://github.com/Robbendebiene/freestyle_speed_dial
repository: https://github.com/Robbendebiene/freestyle_speed_dial
issue_tracker: https://github.com/Robbendebiene/freestyle_speed_dial/issues

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
