name: Example Github-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: example
          # set the corresponding github page base url
          # this is required so the index.html finds the necessary resources
          baseHref: /freestyle_speed_dial/
